# .NET Standard
# Build, apply GitVersion to nuget package and run tests.

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: gitversion/setup@0
  displayName: "GitVersion setup"
  inputs:
    versionSpec: '5.x'

- task: gitversion/execute@0
  displayName: "GitVersion execute"

- task: NuGetCommand@2
  displayName: "Restore solution"
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: "Build"
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:PackageLocation="$(Build.SourcesDirectory)\packages" /p:Version=$(GitVersion.NuGetVersion)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: "Test"
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'

