//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Techtoniq.GHSDatabase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Techtoniq.GHSDatabase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Div 1.1.
        /// </summary>
        internal static string Category_Div1_1 {
            get {
                return ResourceManager.GetString("Category_Div1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Div 1.2.
        /// </summary>
        internal static string Category_Div1_2 {
            get {
                return ResourceManager.GetString("Category_Div1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Div 1.3.
        /// </summary>
        internal static string Category_Div1_3 {
            get {
                return ResourceManager.GetString("Category_Div1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Div 1.4.
        /// </summary>
        internal static string Category_Div1_4 {
            get {
                return ResourceManager.GetString("Category_Div1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Div 1.5.
        /// </summary>
        internal static string Category_Div1_5 {
            get {
                return ResourceManager.GetString("Category_Div1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Div 1.6.
        /// </summary>
        internal static string Category_Div1_6 {
            get {
                return ResourceManager.GetString("Category_Div1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unstable Explosive.
        /// </summary>
        internal static string Category_UnstableExplosive {
            get {
                return ResourceManager.GetString("Category_UnstableExplosive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explosives.
        /// </summary>
        internal static string Class_Explosives {
            get {
                return ResourceManager.GetString("Class_Explosives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flammable Aerosoles.
        /// </summary>
        internal static string Class_FlammableAerosoles {
            get {
                return ResourceManager.GetString("Class_FlammableAerosoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flammable Gases.
        /// </summary>
        internal static string Class_FlammableGases {
            get {
                return ResourceManager.GetString("Class_FlammableGases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flammable Liquids.
        /// </summary>
        internal static string Class_FlammableLiquids {
            get {
                return ResourceManager.GetString("Class_FlammableLiquids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flammable Solids.
        /// </summary>
        internal static string Class_FlammableSolids {
            get {
                return ResourceManager.GetString("Class_FlammableSolids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ghs01 {
            get {
                object obj = ResourceManager.GetObject("ghs01", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unstable explosive..
        /// </summary>
        internal static string H200 {
            get {
                return ResourceManager.GetString("H200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explosive; mass explosion hazard.
        /// </summary>
        internal static string H201 {
            get {
                return ResourceManager.GetString("H201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explosive; severe projection hazard.
        /// </summary>
        internal static string H202 {
            get {
                return ResourceManager.GetString("H202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explosive; fire, blast or projection hazard.
        /// </summary>
        internal static string H203 {
            get {
                return ResourceManager.GetString("H203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire or projection hazard.
        /// </summary>
        internal static string H204 {
            get {
                return ResourceManager.GetString("H204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May mass explode in fire.
        /// </summary>
        internal static string H205 {
            get {
                return ResourceManager.GetString("H205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If medical advice is needed,have product container or label at hand..
        /// </summary>
        internal static string P101 {
            get {
                return ResourceManager.GetString("P101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep out of reach of children..
        /// </summary>
        internal static string P102 {
            get {
                return ResourceManager.GetString("P102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read label before use..
        /// </summary>
        internal static string P103 {
            get {
                return ResourceManager.GetString("P103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danger.
        /// </summary>
        internal static string SignalWord_Danger {
            get {
                return ResourceManager.GetString("SignalWord_Danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string SignalWord_Warning {
            get {
                return ResourceManager.GetString("SignalWord_Warning", resourceCulture);
            }
        }
    }
}
